### ISSUE TITLE
Dump fails for GregTech (GregTechCEu Modern) versions 1.6.0+ on 1.20.1

### ISSUE THREAD

**Issue by guaiacol03** [Prunoideae/ProbeJS#107]
`/probejs dump` fails on 1.20.1 if [GregTechCEu](https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern) v.1.6.0 or 1.6.1 is installed (1.5.4 works fine)

- Kubejs version: 2001.6.5
- Probejs version: 6.0.1
- Loader: NeoForge 47.1.106

Crash log (from _latest.log_):
```
[00:13:58] [Thread-14/ERROR] [probejs/]: Uncaught exception has occurred!
java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 16 on Block{minecraft:water}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.fluids.ForgeFlowingFluid.m_5804_(ForgeFlowingFluid.java:138) ~[forge-1.20.1-47.1.106-universal.jar%23171!/:?] {re:classloading}
	at net.minecraft.world.level.material.FluidState.m_76188_(FluidState.java:96) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,re:mixin}
	at com.probejs.features.rich.fluid.FluidAttribute.serialize(FluidAttribute.java:38) ~[probejs-6.0.1-forge.jar%23164!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at com.probejs.util.json.JArray.addAll(JArray.java:44) ~[probejs-6.0.1-forge.jar%23164!/:?] {re:classloading}
	at com.probejs.features.rich.fluid.RichFluidCompiler.compile(RichFluidCompiler.java:25) ~[probejs-6.0.1-forge.jar%23164!/:?] {re:classloading}
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:117) ~[probejs-6.0.1-forge.jar%23164!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

**Comment by guaiacol03** [comment]
Seems to be patched in GregTech 1.6.2 update
