### ISSUE TITLE
1.19.2 probe is a ram eater

### ISSUE THREAD

**Issue by tizu69** [Prunoideae/ProbeJS#20]
What changed between 1.18.2 and 1.19.2 probe? 1.18.2 worked in a few secs, the new one takes like 200 secs to fail because of missing ram.
```
[08:30:00] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] Docs merged. Started compiling... [32.607s]
[08:30:05] [Render thread/WARN] [journeymap/]: Can't get entityTexture for aquaculture:textures/entity_icon/fish/brown_trout.png
[08:30:20] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2421ms or 48 ticks behind
[08:33:05] [Thread-42/ERROR] [probejs/]: java.lang.OutOfMemoryError: Java heap space
[08:33:05] [JM-task-4/ERROR] [journeymap/]: Unexpected error in ChunkRenderController: java.lang.OutOfMemoryError: Java heap space
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.model.RegionCoord.fromRegionPos(RegionCoord.java:62)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.model.RegionImageSet.getRegionCoord(RegionImageSet.java:110)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.model.RegionImageSet.getChunkImage(RegionImageSet.java:54)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:114)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:125)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:424)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.OutOfMemoryError: Java heap space
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.model.RegionCoord.fromRegionPos(RegionCoord.java:62)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.model.RegionImageSet.getRegionCoord(RegionImageSet.java:110)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.model.RegionImageSet.getChunkImage(RegionImageSet.java:54)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:114)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:125)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:424)
	at TRANSFORMER/journeymap@5.9.3/journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[08:33:05] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] ProbeJS has run into an error! Please check out latest.log and report to GitHub! [217.063s]
```
Yes, the error is reported by JourneyMap, but there's no other error message

**Comment by Prunoideae** [comment]
Can you tell about how many mods you're having when dumping, and how many RAMs you're giving to MC?

Also, you can try to run `/probejs configure toggle_registry_dumps` to disable `registry class resolving` to reduce RAM usage, this feature will try to resolve every item, block registered so you can get completion for a certain type of block or item, but this feature will require a bit too much system resource when running on things like ATM8.

**Comment by tizu69** [comment]
I had about 350 mods installed with 12gb ram. 
`/probejs configure toggle_registry_dumps` worked fine, thanks!
