### ISSUE TITLE
Dump Error

### ISSUE THREAD

**Issue by TheCherry** [Prunoideae/ProbeJS#3]
Dump gives me a error.

MC: 1.18.2
Probe: 2.8.0
Fabric Loader: 0.13.3
Fabric API: 0.51.1

```
[20:32:55] [REI-ReloadPlugins/INFO] (REI) [REI] Reloading Plugin Manager [REIServerPlugin] stage [START], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[20:32:55] [REI-ReloadPlugins/INFO] (REI) [REI] Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 2 fluid support providers in 13ms.
[20:32:55] [REI-ReloadPlugins/INFO] (REI) [REI] Reloaded Plugin Manager [REIClientPlugin] with 1417 entries, 1635 displays, 1 display visibility predicates, 21 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information), 4 exclusion zones and 3 overlay deciders in 65ms.
[20:32:55] [REI-ReloadPlugins/INFO] (REI) [REI] Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 2ms.
[20:32:56] [REI-ReloadPlugins/INFO] (REI) [REI] Reloading Plugin Manager [REIPlugin] stage [END], registered 9 plugins: KubeJSREIPlugin [kubejs], DefaultRuntimePlugin [roughlyenoughitems], DefaultClientRuntimePlugin [roughlyenoughitems], FTBQuestsREIIntegration [ftbquests], REIIntegration [ftblibrary], REIPlugin [toms_storage], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems], DefaultClientPlugin [roughlyenoughitems]
[20:32:56] [REI-ReloadPlugins/INFO] (REI) [REI] Reloading Plugin Manager [REIClientPlugin] stage [END], registered 6 plugins: KubeJSREIPlugin [kubejs], DefaultClientRuntimePlugin [roughlyenoughitems], FTBQuestsREIIntegration [ftbquests], REIIntegration [ftblibrary], REIPlugin [toms_storage], DefaultClientPlugin [roughlyenoughitems]
[20:32:56] [REI-ReloadPlugins/INFO] (REI) [REI] Reloading Plugin Manager [REIServerPlugin] stage [END], registered 3 plugins: DefaultRuntimePlugin [roughlyenoughitems], FabricFluidAPISupportPlugin, DefaultPlugin [roughlyenoughitems]
[20:32:56] [REI-ReloadPlugins/INFO] (REI) [REI] Reloaded Plugin Manager [REIPlugin] with 2 entry types, 5 item comparators, 0 fluid comparators and 2 fluid support providers in 12ms.
[20:32:56] [REI-ReloadPlugins/INFO] (REI) [REI] Reloaded Plugin Manager [REIClientPlugin] with 1417 entries, 1635 displays, 1 display visibility predicates, 21 categories (Crafting, Smelting, Smoking, Blasting, Campfire, Stone Cutting, Fuel, Brewing, Composting, Stripping, Smithing, Anvil, Beacon Base, Beacon Payment, Tilling, Pathing, Waxing, Wax Scraping, Oxidizing, Oxidation Scraping, Information), 4 exclusion zones and 3 overlay deciders in 39ms.
[20:32:56] [REI-ReloadPlugins/INFO] (REI) [REI] Reloaded Plugin Manager [REIServerPlugin] with 4 menu infos in 2ms.
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:333)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Parameter.getParameterizedType(Parameter.java:202)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.info.MethodInfo$ParamInfo.<init>(MethodInfo.java:103)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.info.ConstructorInfo.<init>(ConstructorInfo.java:12)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.info.ClassInfo.<init>(ClassInfo.java:58)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.info.ClassInfo.getOrCache(ClassInfo.java:25)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.info.Walker.touch(Walker.java:53)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.info.Walker.walk(Walker.java:80)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.TypingCompiler.fetchClasses(TypingCompiler.java:167)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.TypingCompiler.compile(TypingCompiler.java:331)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.probejs.ProbeCommands.lambda$register$1(ProbeCommands.java:45)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.command.CommandManager.redirect$zep000$performCommand(CommandManager.java:1047)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.command.CommandManager.execute(CommandManager.java:264)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler.java:1253)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler.java:1237)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayNetworkHandler.onChatMessage(ServerPlayNetworkHandler.java:1220)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket.java:30)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket.java:7)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.ServerTask.run(ServerTask.java:18)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:808)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:165)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:790)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:784)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:116)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:768)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
[20:32:56] [Server thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Prunoideae** [comment]
This problem is weird as it occurs within Java's reflection code, neither I can do much about it nor I can reproduce the problem.

I got the dump fine on Fabric API 0.51.1 and Fabric 0.14.3.
