### ISSUE TITLE
[1.19.2] Dump: Uncaught exception happend in wrapper

### ISSUE THREAD

**Issue by plantiac** [Prunoideae/ProbeJS#37]
[latest.log](https://gist.github.com/plantiac/80fb1f1f2b10f57387f2d2fdd75c3435) dump initiation starts after line 8332, uncaught exception after line 11850

Edit: So I found out that Cooking for Blockheads (Fabric Edition) 1.19.2-13.3.3 tied with it's dependency Balm (Fabric Edition) 1.19.2-4.6.0 causes the issue.

Here's the relevant stacktrace: 
```
[17:15:21] [Render thread/ERROR]: Error:
java.lang.IllegalArgumentException: Cannot convert flowing fluid balm-fabric:milk (net.blay09.mods.balm.fabric.fluid.SimpleMilkFluid@317b47a3) into a still fluid.
	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:48) ~[fabric-transfer-api-v1-2.1.6+413cbbc790-54ac9d7b5c44428e.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:72) ~[fabric-transfer-api-v1-2.1.6+413cbbc790-54ac9d7b5c44428e.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:61) ~[fabric-transfer-api-v1-2.1.6+413cbbc790-54ac9d7b5c44428e.jar:?]
	at com.probejs.util.fabric.PlatformSpecialImpl.getFluidSprite(PlatformSpecialImpl.java:43) ~[probejs-5.3.1-fabric.jar:?]
	at com.probejs.rich.ImageHelper.renderFluid(ImageHelper.java:66) ~[probejs-5.3.1-fabric.jar:?]
	at com.probejs.rich.ImageHelper.getFromFluid(ImageHelper.java:40) ~[probejs-5.3.1-fabric.jar:?]
	at com.probejs.rich.fluid.RichFluidCompiler.render(RichFluidCompiler.java:38) ~[probejs-5.3.1-fabric.jar:?]
	at com.probejs.ProbeCommands.lambda$triggerRender$0(ProbeCommands.java:70) ~[probejs-5.3.1-fabric.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1129) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]
```

**Comment by Prunoideae** [comment]
Will try to fix some time later.
