### ISSUE TITLE
The console throws an error after running dump.

### ISSUE THREAD

**Issue by EvanHsieh0415** [Prunoideae/ProbeJS#38]
<details>
  <summary>Logs snippet</summary>

```java
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:333)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Parameter.getParameterizedType(Parameter.java:202)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:142)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ConstructorInfo.<init>(ConstructorInfo.java:12)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.<init>(ClassInfo.java:74)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.getOrCache(ClassInfo.java:35)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.touch(Walker.java:59)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.walk(Walker.java:99)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.fetchClasses(DocCompiler.java:175)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:346)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:333)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Parameter.getParameterizedType(Parameter.java:202)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:142)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ConstructorInfo.<init>(ConstructorInfo.java:12)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.<init>(ClassInfo.java:74)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.getOrCache(ClassInfo.java:35)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.touch(Walker.java:59)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.walk(Walker.java:99)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.fetchClasses(DocCompiler.java:175)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:346)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:333)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Parameter.getParameterizedType(Parameter.java:202)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:142)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ConstructorInfo.<init>(ConstructorInfo.java:12)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.<init>(ClassInfo.java:74)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.getOrCache(ClassInfo.java:35)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.touch(Walker.java:59)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.walk(Walker.java:99)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.fetchClasses(DocCompiler.java:175)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:346)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:333)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Parameter.getParameterizedType(Parameter.java:202)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:142)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ConstructorInfo.<init>(ConstructorInfo.java:12)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.<init>(ClassInfo.java:74)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.getOrCache(ClassInfo.java:35)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.touch(Walker.java:59)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.walk(Walker.java:99)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.fetchClasses(DocCompiler.java:175)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:346)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:333)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.reflect.Parameter.getParameterizedType(Parameter.java:202)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:142)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.MethodInfo$ParamInfo.<init>(MethodInfo.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ConstructorInfo.<init>(ConstructorInfo.java:12)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.<init>(ClassInfo.java:74)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.ClassInfo.getOrCache(ClassInfo.java:35)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.touch(Walker.java:59)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.jdoc.java.Walker.walk(Walker.java:99)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.fetchClasses(DocCompiler.java:175)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:346)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:135)
[10:45:36] [Thread-20/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

- Logs: https://mclo.gs/udnOebj

**Comment by Prunoideae** [comment]
This is not an error in the dump, the message was caught and printed out for some debugging purposes.
