### ISSUE TITLE
[1.19.2] Dump: Uncaught exception happened in wrapper

### ISSUE THREAD

**Issue by CelestialAbyss** [Prunoideae/ProbeJS#39]
ProbeJS version: 5.3.1
KubeJS version: 1902.6.2-build.37
Forge version: 43.3.2

```
[29Oct2023 10:32:32.698] [Thread-66/ERROR] [probejs/]: Uncaught exception has occurred!
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 25 column 2 path $.[json]
	at com.google.gson.Gson.fromJson(Gson.java:978) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:901) ~[gson-2.8.9.jar%23127!/:?]
	at com.probejs.compiler.DocCompiler.writeMergedConfig(DocCompiler.java:277) ~[probejs-5.3.1-forge.jar%23625!/:?]
	at com.probejs.compiler.DocCompiler.compileVSCodeConfig(DocCompiler.java:206) ~[probejs-5.3.1-forge.jar%23625!/:?]
	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:399) ~[probejs-5.3.1-forge.jar%23625!/:?]
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:123) ~[probejs-5.3.1-forge.jar%23625!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 25 column 2 path $.[json]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:504) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:683) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%23127!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%23127!/:?]
	... 6 more
```

You can view the full latest.log file [here](https://gist.github.com/CelestialAbyss/2719431435d993da3b7d4cb74e862b9d) if needed.

**Comment by Prunoideae** [comment]
Your `settings.json` in `.vscode` folder under your `.minecraft` folder is not a valid JSON file (probably because it's JSONC or whatever), this caused ProbeJS failed to merge configs necessary to setup projects into into it.
