### ISSUE TITLE
[1.19.2] Failed to process enum: org.apache.logging.log4j.core.async.EventRoute

### ISSUE THREAD

**Issue by Yarden-zamir** [Prunoideae/ProbeJS#42]
The dumping thread seems to crash right after the `classes fetched` step, something relating to log4j? 

<details><summary>Details</summary>
<p>

```java
[09Nov2023 17:47:00.312] [Thread-26/WARN] [probejs/]: Failed to process enum: org.apache.logging.log4j.core.async.EventRoute
[09Nov2023 17:47:00.353] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Classes fetched. [8.594s]
[09Nov2023 17:47:00.375] [Thread-26/ERROR] [probejs/]: Uncaught exception has occurred!
java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/typings/JsInfo
	at com.probejs.jdoc.document.DocumentMethod.lambda$fromJava$2(DocumentMethod.java:68) ~[probejs-5.3.0-forge.jar%23231!/:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at com.probejs.jdoc.document.DocumentMethod.fromJava(DocumentMethod.java:68) ~[probejs-5.3.0-forge.jar%23231!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.probejs.jdoc.document.DocumentClass.fromJava(DocumentClass.java:71) ~[probejs-5.3.0-forge.jar%23231!/:?]
	at com.probejs.jdoc.Manager.loadJavaClasses(Manager.java:90) ~[probejs-5.3.0-forge.jar%23231!/:?]
	at com.probejs.compiler.DocCompiler.compile(DocCompiler.java:355) ~[probejs-5.3.0-forge.jar%23231!/:?]
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:122) ~[probejs-5.3.0-forge.jar%23231!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.latvian.mods.kubejs.typings.JsInfo
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 24 more
``` 

</p>
</details>

**Comment by Prunoideae** [comment]
Enum errors should be ignored. What's your KubeJS version? You seem to be from a version of KubeJS where no `JsInfo` is present.

**Comment by Yarden-zamir** [comment]
```
KubeJS Forge 1902.6.2-build.39
```
which, from what I can tell, is the latest.
By ignored you mean that probejs should ignore them?

**Comment by Prunoideae** [comment]
Wait, what's your ProbeJS version? I just remembered that JsInfo was renamed to Info in a certain KJS update, and ProbeJS was fixed then. You should check your ProbeJS version.

**Comment by Yarden-zamir** [comment]
[v5.3.0](https://github.com/Prunoideae/ProbeJS/releases/tag/v5.3.0) as from what I understood, that was the last 1.19.2 version, now starting to think that was a bad guess 😅

**Comment by Prunoideae** [comment]
![image](https://github.com/Prunoideae/ProbeJS/assets/24620047/2aacbb3b-3202-43d1-b0a0-bafe28d88b7b)

Try this then.

**Comment by Yarden-zamir** [comment]
I'm not on curse forge, so need to use github releases. Or anything else not on curse cdn

**Comment by Prunoideae** [comment]
Ok, I just released the new version.

**Comment by Yarden-zamir** [comment]
Ah awesome, thank you, i'll give that a go. 
[unrelated side question]Is there a difference between the 1.19.2 and the 1.20 versions now?

**Comment by Prunoideae** [comment]
> Is there a difference between the 1.19.2 and the 1.20 versions now?

The most major one is that it supports 1.20, given how much KubeJS has changed.

A performance fix for packs with 200+ mods was implemented but not released yet. I'm currently quite busy on some other projects, and will probably rewrite the typing structure again after things are settled.

**Comment by Yarden-zamir** [comment]
Awesome, works perfectly. Thank you! The original issue's title should have been "missing github release for latest 1.19.2 release"

**Comment by Yarden-zamir** [comment]
What was the fix to help with big packs? Also, how many times have you already rewritten typing structure? By your wording it sounds like a few

**Comment by Prunoideae** [comment]
The fix is to split the original large `global.d.ts` into a few chunks so VSCode will have better lookup performance when dealing with such packs.

Typing was rewritten two times already. 1.18.2 to 1.19.2 was the first, and 6.0 to 6.1 was the second.

**Comment by Yarden-zamir** [comment]
Cool. Another unrelated thing that maybe should be an issue. Can you upload the mod on modrinth? Or is there a reason it's not there or something.
