### ISSUE TITLE
[1.20.1]Uncaught exception has occured.

### ISSUE THREAD

**Issue by Tollainmear** [Prunoideae/ProbeJS#45]
hi, when I type `probejs dump` and wait for it's generation, I got this message as return:
`Uncaught exception has occurred!`
```
[11Dec2023 01:07:01.699] [Server thread/INFO] [KubeJS Server/]: Server resource reload complete!
[1112月2023 01:07:01.712] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Reloaded with no KubeJS errors!
[11Dec2023 01:07:02.475] [Thread-58/ERROR] [probejs/]: Uncaught exception has occurred!
java.lang.NullPointerException: Registry Object not present: tfc:dark_chocolate
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:572) ~[forge-1.20.1-47.2.17-universal.jar%23697!/:?]
	at net.minecraftforge.fluids.ForgeFlowingFluid.getFluidType(ForgeFlowingFluid.java:63) ~[forge-1.20.1-47.2.17-universal.jar%23697!/:?]
	at dev.architectury.hooks.fluid.forge.FluidStackHooksImpl.getName(FluidStackHooksImpl.java:43) ~[%5B前置%5Darchitectury-9.1.12-forge.jar%23495!/:?]
	at dev.architectury.hooks.fluid.FluidStackHooks.getName(FluidStackHooks.java) ~[%5B前置%5Darchitectury-9.1.12-forge.jar%23495!/:?]
	at dev.architectury.fluid.FluidStack.getName(FluidStack.java:189) ~[%5B前置%5Darchitectury-9.1.12-forge.jar%23495!/:?]
	at com.probejs.rich.fluid.FluidAttribute.serialize(FluidAttribute.java:26) ~[%5BKJS%5Dprobejs-5.5.0-forge.jar%23437!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.probejs.util.json.JArray.addAll(JArray.java:41) ~[%5BKJS%5Dprobejs-5.5.0-forge.jar%23437!/:?]
	at com.probejs.rich.fluid.RichFluidCompiler.compile(RichFluidCompiler.java:25) ~[%5BKJS%5Dprobejs-5.5.0-forge.jar%23437!/:?]
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:130) ~[%5BKJS%5Dprobejs-5.5.0-forge.jar%23437!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

So I'm trying to give a feed back and asking for help.

Thanks for your work.

[latest.log](https://github.com/Prunoideae/ProbeJS/files/13628634/latest.log)

**Comment by Prunoideae** [comment]
This looks like an issue of other mods... They should have fluid registered.

Anyway, I'll fix it later, but probably not a priority.

**Comment by Tollainmear** [comment]
> This looks like an issue of other mods... They should have fluid registered.
> 
> Anyway, I'll fix it later, but probably not a priority.

I appreciate that :)

**Comment by Tollainmear** [comment]
Hi @Prunoideae 
Another uncaught exception occured while executing `/probejs dump`

```
[11Dec2023 22:54:27.768] [Thread-23/ERROR] [probejs/]: Uncaught exception has occurred!
java.nio.file.NoSuchFileException: D:\Games\Karoglan_TFCLife\.minecraft\versions\Karoglan-TFC-Create\.vscode\probe.code-snippets
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at java.nio.file.Files.newBufferedWriter(Files.java:3008) ~[?:?]
	at java.nio.file.Files.newBufferedWriter(Files.java:3056) ~[?:?]
	at com.probejs.compiler.SnippetCompiler.compile(SnippetCompiler.java:130) ~[%5BKJS%5Dprobejs-5.5.0-forge.jar%23166!/:?]
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:128) ~[%5BKJS%5Dprobejs-5.5.0-forge.jar%23166!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11Dec2023 22:54:27.771] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Reloaded with no KubeJS errors!
[11Dec2023 22:54:27.771] [Server thread/INFO] [KubeJS Server/]: Server resource reload complete!
```

it seems like not a same problem, do you need entire log file?

**Comment by Prunoideae** [comment]
This should not be a problem on the mod's end. Did you delete the `.vscode` folder after it was created? It's necessary for ProbeJS to set up and configure the environment.

If you didn't, the only possibility is that ProbeJS can't create the folder at that specific location, which is some sort of file permission problem of your PC.

**Comment by Tollainmear** [comment]
> This should not be a problem on the mod's end. Did you delete the `.vscode` folder after it was created? It's necessary for ProbeJS to set up and configure the environment.
> 
> If you didn't, the only possibility is that ProbeJS can't create the folder at that specific location, which is some sort of file permission problem of your PC.

Thanks for your reply, I'll check it later~

**Comment by osirisgothra** [comment]
im not sure if its really related but wrapper exceptions solved as of today, since I said I would post any workarounds I'll do that, but its kinda long so its [posted here instead](https://www.reddit.com/r/feedthebeast/comments/1fjy7b0/how_to_fix_uncaught_exception_problems_in_probejs/)
