### ISSUE TITLE
Uncaught exception happened in wrapper

### ISSUE THREAD

**Issue by Rimevel** [Prunoideae/ProbeJS#56]
Game version: 1.19.2
ProbeJS version: 5.3.4
KubeJS version: 1902.6.2-build59

I get the error in the title every time I try to do a dump with the dump command 😢 

This is the relevant error in the log:

```
[15:56:51] [Thread-30/ERROR] [probejs/]: Uncaught exception has occurred!
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:77) ~[guava-31.0.1-jre.jar%23116!/:?] {}
	at net.lyof.sortilege.items.custom.potion.AntidotePotionItem.m_7626_(AntidotePotionItem.java:45) ~[Sortilege-1.19.2-1.3.1.jar%23282!/:1.0] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:607) ~[client-1.19.2-20220805.130853-srg.jar%23295!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:forge-morecreativetabs.mixins.json:ItemStackMixin,pl:mixin:APP:necronomicon.forge.mixins.json:AnimatedItemNameMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:sortilege.mixins.json:MixinItemStack,pl:mixin:A}
	at com.probejs.rich.item.ItemAttribute.serialize(ItemAttribute.java:46) ~[probejs-5.3.4-forge.jar%23274!/:?] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at com.probejs.util.json.JArray.addAll(JArray.java:41) ~[probejs-5.3.4-forge.jar%23274!/:?] {re:classloading}
	at com.probejs.rich.item.RichItemCompiler.compile(RichItemCompiler.java:26) ~[probejs-5.3.4-forge.jar%23274!/:?] {re:classloading}
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:101) ~[probejs-5.3.4-forge.jar%23274!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by Prunoideae** [comment]
I see... There'll be a fix on the ProbeJS side sometime later.

**Comment by Rimevel** [comment]
Seem to be the Sortilege mod doing something wierd 🤔 They add a 4th type of potion (antidote) to the game. So maybe that is tripping things up.

**Comment by Prunoideae** [comment]
Yes, it is. ProbeJS will try to get the localized name for all items in the game, but I didn't expect there'll be an item to throw an error here.

**Comment by Rimevel** [comment]
@Prunoideae Just wanted to check if you have had time to fix this yet? :)
