### ISSUE TITLE
[1.19.2] Uncaught exception has occurred

### ISSUE THREAD

**Issue by plantiac** [Prunoideae/ProbeJS#58]
Again related to Balm library and flowing/still fluid conversion. Error is at line 27328

[latest.log](https://github.com/Prunoideae/ProbeJS/files/14734296/latest.log)

**Comment by momosundeass** [comment]
Same error
```
[18:25:01] [Thread-81/ERROR]: Uncaught exception has occurred!
java.lang.IllegalArgumentException: Cannot convert flowing fluid balm-fabric:milk (net.blay09.mods.balm.fabric.fluid.SimpleMilkFluid@75bbe551) into a still fluid.
	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:48) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-394e3c6b4f860686.jar:?]
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:72) ~[fabric-transfer-api-v1-3.3.5+8dd72ea377-394e3c6b4f860686.jar:?]
	at dev.architectury.fluid.fabric.FluidStackImpl.create(FluidStackImpl.java:67) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.fluid.fabric.FluidStackImpl.create(FluidStackImpl.java:33) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.fluid.FluidStack.<init>(FluidStack.java:44) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.fluid.FluidStack.create(FluidStack.java:94) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.fluid.FluidStack.create(FluidStack.java:86) ~[architectury-9.2.14-fabric.jar:?]
	at dev.architectury.fluid.FluidStack.create(FluidStack.java:90) ~[architectury-9.2.14-fabric.jar:?]
	at com.probejs.rich.fluid.FluidAttribute.<init>(FluidAttribute.java:21) ~[probejs-6.0.0-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at com.google.common.collect.CollectSpliterators$1.lambda$forEachRemaining$1(CollectSpliterators.java:128) ~[guava-31.1-jre.jar:?]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
	at com.google.common.collect.CollectSpliterators$1.forEachRemaining(CollectSpliterators.java:128) ~[guava-31.1-jre.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.probejs.util.json.JArray.addAll(JArray.java:41) ~[probejs-6.0.0-fabric.jar:?]
	at com.probejs.rich.fluid.RichFluidCompiler.compile(RichFluidCompiler.java:25) ~[probejs-6.0.0-fabric.jar:?]
	at com.probejs.ProbeCommands.lambda$triggerDump$4(ProbeCommands.java:117) ~[probejs-6.0.0-fabric.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

fabric + mc 1.20.1
kubejs 2001.6.5-build.14
probejs 6.0.0

Edited: Remove balm and everything working find
