### ISSUE TITLE
error executing command /probejs dump

### ISSUE THREAD

**Issue by pafeuu** [Prunoideae/ProbeJS#78]
I'am a complete noob when it comes to reading logs so can't really figure out how to fix it. Saw illager invasion mod coming up a few times but even when i disabled it nothing changed.

```
[08:21:29] [Render thread/INFO]: [System] [CHAT] ProbeJS dump started.
[08:21:30] [Render thread/INFO]: [System] [CHAT] Snippets for VSCode generated.
[08:21:30] [Render thread/INFO]: [System] [CHAT] An unexpected error occurred trying to execute that command
[08:21:30] [Render thread/ERROR]: Error executing client command "probejs dump"
java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: fuzs.illagerinvasion.mixin.SpellcasterIllagerImpl is in a defined mixin package fuzs.illagerinvasion.mixin.* owned by illagerinvasion.common.mixins.json and cannot be referenced directly
	at moe.wolfgirl.probejs.GameEvents.lambda$registerCommand$3(GameEvents.java:77) ~[probejs-7.0.1-forge.jar%23543!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23124!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.1.8.jar%23124!/:?]
	at net.minecraftforge.client.ClientCommandHandler.runCommand(ClientCommandHandler.java:161) ~[forge-1.20.1-47.2.30-universal.jar%23606!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_246623_(ClientPacketListener.java:2418) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_241797_(ChatScreen.java:223) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_7933_(ChatScreen.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:379) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:369) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:462) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:461) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%2387!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2387!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23601!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: fuzs.illagerinvasion.mixin.SpellcasterIllagerImpl is in a defined mixin package fuzs.illagerinvasion.mixin.* owned by illagerinvasion.common.mixins.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaringClass0(Native Method) ~[?:?]
	at java.lang.Class.getEnclosingClass(Unknown Source) ~[?:?]
	at sun.reflect.annotation.AnnotatedTypeFactory.nestingForType(Unknown Source) ~[?:?]
	at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedTypes(Unknown Source) ~[?:?]
	at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedInterfaces(Unknown Source) ~[?:?]
	at java.lang.Class.getAnnotatedInterfaces(Unknown Source) ~[?:?]
	at moe.wolfgirl.probejs.lang.java.clazz.Clazz.<init>(Clazz.java:61) ~[probejs-7.0.1-forge.jar%23543!/:?]
	at moe.wolfgirl.probejs.lang.java.ClassRegistry.discoverClasses(ClassRegistry.java:103) ~[probejs-7.0.1-forge.jar%23543!/:?]
	at moe.wolfgirl.probejs.ProbeDump.trigger(ProbeDump.java:97) ~[probejs-7.0.1-forge.jar%23543!/:?]
	at moe.wolfgirl.probejs.GameEvents.lambda$registerCommand$3(GameEvents.java:75) ~[probejs-7.0.1-forge.jar%23543!/:?]
	... 36 more

```
After I disabled the mod
```
[08:27:18] [Render thread/INFO]: [System] [CHAT] ProbeJS dump started.
[08:27:18] [Render thread/INFO]: [System] [CHAT] An unexpected error occurred trying to execute that command
[08:27:18] [Render thread/ERROR]: Error executing client command "probejs dump"
java.lang.RuntimeException: java.util.ConcurrentModificationException
	at moe.wolfgirl.probejs.GameEvents.lambda$registerCommand$3(GameEvents.java:77) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%23109!/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.1.8.jar%23109!/:?]
	at net.minecraftforge.client.ClientCommandHandler.runCommand(ClientCommandHandler.java:161) ~[forge-1.20.1-47.2.30-universal.jar%23604!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_246623_(ClientPacketListener.java:2418) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_241797_(ChatScreen.java:223) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.gui.screens.ChatScreen.m_7933_(ChatScreen.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:379) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:369) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:462) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:461) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23130!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2396!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23130!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23599!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.30.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:?]
	at java.util.AbstractCollection.addAll(Unknown Source) ~[?:?]
	at java.util.HashSet.<init>(Unknown Source) ~[?:?]
	at moe.wolfgirl.probejs.GlobalStates.lambda$static$0(GlobalStates.java:25) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.docs.SpecialTypes.addVSCodeSnippets(SpecialTypes.java:35) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.docs.ProbeBuiltinDocs.lambda$addVSCodeSnippets$6(ProbeBuiltinDocs.java:91) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.docs.ProbeBuiltinDocs.forEach(ProbeBuiltinDocs.java:50) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.docs.ProbeBuiltinDocs.addVSCodeSnippets(ProbeBuiltinDocs.java:91) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.plugin.BuiltinProbeJSPlugin.addVSCodeSnippets(BuiltinProbeJSPlugin.java:103) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.lang.snippet.SnippetDump.lambda$fromDocs$0(SnippetDump.java:27) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.plugin.ProbeJSPlugin.lambda$forEachPlugin$0(ProbeJSPlugin.java:31) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at dev.latvian.mods.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:116) ~[kubejs-forge-2001.6.5-build.14.jar%23496!/:2001.6.5-build.14]
	at moe.wolfgirl.probejs.plugin.ProbeJSPlugin.forEachPlugin(ProbeJSPlugin.java:29) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.lang.snippet.SnippetDump.fromDocs(SnippetDump.java:27) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.ProbeDump.trigger(ProbeDump.java:75) ~[probejs-7.0.1-forge.jar%23541!/:?]
	at moe.wolfgirl.probejs.GameEvents.lambda$registerCommand$3(GameEvents.java:75) ~[probejs-7.0.1-forge.jar%23541!/:?]
	... 36 more
```

**Comment by Prunoideae** [comment]
Use probejs v6.x.
